name: Build LaTeX and Upload Artifact

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build LaTeX full_version
      run: make compile 
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: PDFs
        path: pdf_folder/
