name: Build LaTeX and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        args: "-lualatex -file-line-error -interaction=nonstopmode"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: main.pdf

    - name: Get Release ID
      id: get_release_id
      run: echo "::set-output name=release_id::${{ steps.create_release.outputs.id }}"

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: main.pdf
        asset_name: main.pdf
        asset_content_type: application/pdf
