name: Build LaTeX and Upload Artifact

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build LaTeX full_version
      run: make compile
    - name: Upload PDFs
      uses: actions/upload-artifact@v3
      with:
        name: PDFs
        path: pdf_folder/*.pdf
