name: Build LaTeX and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build LaTeX full_version
      uses: xu-cheng/latex-action@v3
      with:
        root_file: full_version/main.tex
        args: "-lualatex -file-line-error -interaction=nonstopmode"
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: Full Version PDF
        path: full_version/main.pdf