name: Build LaTeX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
  
    - name: Build LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        asset_path: main.pdf
