name: Build LaTeX and Upload Artifact

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build LaTeX documents
      run: make compile
    - name: Clean LaTeX build files
      run: make clean
    - name: Create PDF folder
      run: make pdf_folder
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: PDFs
        path: pdf_folder/
