name: Release on tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: "-lualatex -file-line-error -interaction=nonstopmode"
      - name: Release PDF
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf